In [2]:
import numpy as np 
import netCDF4 as Dataset
import xarray as xr

In [3]:
url = 'http://www.ncei.noaa.gov/thredds/dodsC/gfs-003-files/201903/20190306/gfs_3_20190306_1200_384.grb2'
ds = xr.open_dataset(url, engine='netcdf4')  # or engine='pydap'

In [4]:
wvs=ds.variables["v-component_of_wind_sigma"]
a=wvs.values
a.astype


<function ndarray.astype>

In [5]:
np.save('component_of_wind_sigma', a)
loaded_array = np.load('component_of_wind_sigma.npy')

loaded_array[:,:,180,350 ]

# np.savetxt('test.csv',a,delimiter=',', fmt=('%f, %f, %f ,%f'))

# import pandas as pd 
# pd.DataFrame(a).to_csv("file.csv")

array([[-0.05126221]], dtype=float32)

In [6]:
ds.Absolute_vorticity_isobaric.lon

<xarray.DataArray 'lon' (lon: 360)>
array([  0.,   1.,   2., ..., 357., 358., 359.], dtype=float32)
Coordinates:
  * lon      (lon) float32 0.0 1.0 2.0 3.0 4.0 ... 355.0 356.0 357.0 358.0 359.0
    reftime  datetime64[ns] ...
Attributes:
    units:    degrees_east

In [7]:
wvs


<xarray.Variable (time: 1, sigma: 1, lat: 181, lon: 360)>
array([[[[ 1.158738, ...,  1.238738],
         ...,
         [-0.831262, ..., -0.751262]]]], dtype=float32)
Attributes:
    long_name:                      v-component of wind @ Sigma level
    units:                          m/s
    abbreviation:                   VGRD
    grid_mapping:                   LatLon_Projection
    Grib_Variable_Id:               VAR_0-2-3_L104
    Grib2_Parameter:                [0 2 3]
    Grib2_Parameter_Discipline:     Meteorological products
    Grib2_Parameter_Category:       Momentum
    Grib2_Parameter_Name:           v-component of wind
    Grib2_Level_Type:               104
    Grib2_Level_Desc:               Sigma level
    Grib2_Generating_Process_Type:  Forecast

In [8]:
#  lat, lon = 64.1353, -21.8952

ds.Temperature_sigma.lat

<xarray.DataArray 'lat' (lat: 181)>
array([ 90.,  89.,  88.,  87.,  86.,  85.,  84.,  83.,  82.,  81.,  80.,  79.,
        78.,  77.,  76.,  75.,  74.,  73.,  72.,  71.,  70.,  69.,  68.,  67.,
        66.,  65.,  64.,  63.,  62.,  61.,  60.,  59.,  58.,  57.,  56.,  55.,
        54.,  53.,  52.,  51.,  50.,  49.,  48.,  47.,  46.,  45.,  44.,  43.,
        42.,  41.,  40.,  39.,  38.,  37.,  36.,  35.,  34.,  33.,  32.,  31.,
        30.,  29.,  28.,  27.,  26.,  25.,  24.,  23.,  22.,  21.,  20.,  19.,
        18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.,   9.,   8.,   7.,
         6.,   5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,
        -6.,  -7.,  -8.,  -9., -10., -11., -12., -13., -14., -15., -16., -17.,
       -18., -19., -20., -21., -22., -23., -24., -25., -26., -27., -28., -29.,
       -30., -31., -32., -33., -34., -35., -36., -37., -38., -39., -40., -41.,
       -42., -43., -44., -45., -46., -47., -48., -49., -50., -51., -52., -53.,
       -54., -55

In [9]:
import datetime as dt
import xarray as xr
date = dt.datetime.now()
year = '{:04d}'.format(2019)
month='{:02d}'.format(3)
day='{:02d}'.format(6)
horizon_start = 0;
horizon = 26;
hours = ['00', '06', '12', '18']

In [ ]:
for j in hours:
    jstr = str(j);
    for k in range(horizon_start,horizon):
        kstr = "{0:0=3d}".format(3 * k)
        url = 'http://www.ncei.noaa.gov/thredds/dodsC/gfs-003-files/'+year+month+'/'+year+month+day+'/gfs_3_'+year+month+day+'_'+jstr+'00_'+kstr+'.grb2'
        nc = xr.open_dataset(url, engine='netcdf4')
        #v-component_of_wind_height_above_ground
        wvh=nc.variables['v-component_of_wind_height_above_ground']
        wvh_value=wvh.values
        v_component_of_wind_height_above_ground_80m = wvh_value[0,1,25,68]
        print(v_component_of_wind_height_above_ground_80m)
        wuh=nc.variables['u-component_of_wind_height_above_ground']
        wuh_value=wuh.values
        u_component_of_wind_height_above_ground_80m = wuh_value[0,1,25,68]
        print(u_component_of_wind_height_above_ground_80m)

6.9132447
2.7937646
8.995501
0.97124267
10.751675
-1.473645
13.334048
-2.4514942
14.217517
-1.8456787
12.807407
-1.1448584
10.910884
-0.4692505
10.068103
-0.57351804
8.635881
-1.2174
6.8028393
3.9424438
5.397429
10.614014
0.15925048
8.2430105
-4.9108033
6.424519
-8.033091
12.292388
-9.512315
13.197466
-5.869104
13.321895
-0.6758789
12.226797
1.217063
10.935761
1.8582081
8.921928
3.2371314
7.6953344
-1.6078857
8.040693
0.16937256
7.1278343
-3.3028393
7.6470046
-1.408042
7.7856984
1.13094
7.0456667
4.3209767
5.4877224
11.7388525
-1.405918
13.460249
