In [9]:
import numpy as np 
B= np.array([1,2,3])
A = np.zeros(10)
A


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
C= np.zeros([10,10])
C

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
O= np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [20]:
R = np.random.random((10,10))
R 

array([[ 0.22770006,  0.41146264,  0.55628652,  0.43913964,  0.3626531 ,
         0.77246973,  0.04186902,  0.18736128,  0.97980123,  0.23914167],
       [ 0.50005174,  0.8451346 ,  0.71281927,  0.13092204,  0.6424768 ,
         0.41134326,  0.924347  ,  0.9255945 ,  0.95642199,  0.48233186],
       [ 0.30396599,  0.92469969,  0.89748543,  0.76769331,  0.41048918,
         0.54075595,  0.03332361,  0.42349086,  0.85964315,  0.3958141 ],
       [ 0.20262197,  0.61880366,  0.11088947,  0.92614812,  0.81703415,
         0.58914371,  0.78343862,  0.8211943 ,  0.99238431,  0.44972262],
       [ 0.08215419,  0.9446503 ,  0.33065135,  0.81645363,  0.18248621,
         0.00340488,  0.23752474,  0.5138846 ,  0.89825534,  0.65029484],
       [ 0.10133871,  0.11463038,  0.5445193 ,  0.83954822,  0.14805189,
         0.93086055,  0.77084971,  0.17099601,  0.25226046,  0.07673271],
       [ 0.11418114,  0.96101864,  0.24540064,  0.1064541 ,  0.40234254,
         0.6530037 ,  0.35293786,  0.74243104

In [23]:
G = np.random.randn(10,10)
G

array([[ 0.34302557,  0.27843822, -0.36813721,  0.26462146, -0.18609719,
         0.7518126 , -1.11351277, -0.02296549,  0.75801588,  1.20009243],
       [-0.83669668,  1.12235506, -1.43253591,  1.04257831, -0.03670725,
        -0.14909538, -0.53068808,  0.49845944,  1.70437592, -0.56183216],
       [-0.81489485,  0.21324596,  0.01459177,  1.09322558,  2.33764133,
        -1.26142216, -0.45306957,  0.51999615, -0.25530921,  0.90815312],
       [-0.11520428,  1.22607597,  1.22349944,  0.16653112, -1.16664441,
         1.13847789,  0.63547665, -0.68087353, -0.9314953 , -0.67880329],
       [ 1.08375343,  0.60454872,  0.42408951,  1.0157983 , -0.97980855,
         0.50761512,  1.2846154 ,  1.39828533,  0.5382552 ,  0.07855617],
       [ 0.72343922, -0.66568626, -0.12666104, -0.42715626,  0.27846514,
         0.78488046, -2.2145913 ,  0.01429985, -0.33456088, -0.21636138],
       [-1.56057467,  0.60615474,  0.35685542, -2.15036189, -1.02895585,
         1.59078046,  0.95631864,  0.54074495

In [25]:
G.mean()

0.077785313380777946

In [27]:
G.var()

0.80179887211233447

In [36]:

E = np.array([[1,2],[3,4]])
E

array([[1, 2],
       [3, 4]])

In [38]:
#Inverse of matrix

Einv = np.linalg.inv(E)
Einv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [41]:
#Identity matrix
Einv.dot(E)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [42]:
np.diag(E)

array([1, 4])

In [44]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [45]:
h= np.array([1,2])
j= np.array([3,4])

In [46]:
np.outer(h,j)

array([[3, 4],
       [6, 8]])

In [47]:
np.inner(h,j)

11

In [49]:
h.dot(j)

11

array([1, 2, 3])