In [1]:
#Let
#X1 number of childern X2= number of adults
#X1+X2= 2200
#1.5X1 + 4X2= 5050

    

In [2]:
import numpy as np

A = np.array([[1,1],[1.5,4]])
A

array([[ 1. ,  1. ],
       [ 1.5,  4. ]])

In [4]:
B= np.array([2200,5050])
B

array([2200, 5050])

In [5]:
x= np.linalg.inv(A).dot(B)
x

array([ 1500.,   700.])

In [6]:
x= np.linalg.solve(A,B)
x

array([ 1500.,   700.])