In [20]:
import numpy as np


In [44]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [45]:
B= np.array([1,2])
B

array([1, 2])

In [46]:
#problem is Ax= b 
#solution is
#Matrix inverse 
#Matrix multiplecation 

In [50]:
x = np.linalg.inv(A).dot(B)
x

array([  2.22044605e-16,   5.00000000e-01])

In [48]:
#another way to solve this is use "solve" function

x= np.linalg.solve(A,B)
x

array([ 0. ,  0.5])