In [4]:
import numpy as np

In [5]:
L= [1,2,3]

In [6]:
A= np.array([1,2,3])

In [7]:
for e in L:
    print(e)

1
2
3


In [8]:
for i in A:
    print(i)

1
2
3


In [9]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [14]:
L =L + [5]

In [15]:
L


[1, 2, 3, 4, 5]

In [16]:
L2 =[]

In [17]:
for e in L:
    L2.append(e+e)

In [18]:
L2

[2, 4, 6, 8, 10]

In [19]:
A+A


array([2, 4, 6])

In [22]:
L2 = []
for e in L:
    L2.append(e*e)
L2

[1, 4, 9, 16, 25]

In [25]:
A**2

array([1, 4, 9], dtype=int32)

In [24]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [26]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])